name: Workflow Notifications

on:
  workflow_run:
    workflows: [ "Test Workflow Failed", "Test Workflow Succeeded" ]

jobs:
  notifications:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        smtp-server: smtp.gmail.com
        smtp-user: GitHubRangers@gmail.com
        smtp-password: ${{ secrets.SMTP_PASSWORD }}
        configuration: ./.github/workflow-notifications.yml
